#!/bin/bash
# Claude Web 功能演示脚本

clear
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║          🎉 Claude Web - 功能完整版 v2.0.0 🎉             ║"
echo "║                                                            ║"
echo "║              类似 Claude Code 的网页应用                   ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✨ 新增功能："
echo ""
echo "  🤖 多模型支持"
echo "     • Claude Sonnet 4.5 (平衡)"
echo "     • Claude Opus 4.6 (最强)"
echo "     • Claude Haiku 3.5 (最快)"
echo ""
echo "  ⌨️  命令系统"
echo "     • /help - 显示帮助"
echo "     • /model - 切换模型"
echo "     • /clear - 清除历史"
echo "     • /tools - 查看工具"
echo ""
echo "  📋 会话管理"
echo "     • 🗑️ 一键清除历史"
echo "     • 💾 导出对话为 Markdown"
echo ""
echo "  🛠️  9 个强大工具"
echo "     • bash, read_file, write_file, edit_file"
echo "     • glob, grep, list_directory"
echo "     • web_fetch, web_search (新增)"
echo ""
echo "────────────────────────────────────────────────────────────"
echo ""
echo "📖 快速开始："
echo ""
echo "  1. 访问: http://localhost:5000"
echo "  2. 登录: junner / xingfu@1984"
echo "  3. 输入: /help"
echo ""
echo "────────────────────────────────────────────────────────────"
echo ""
echo "💡 使用示例："
echo ""
echo "  基础对话："
echo "    你好，请介绍一下你自己"
echo ""
echo "  切换模型："
echo "    /model opus"
echo ""
echo "  文件操作："
echo "    读取 app.py 文件"
echo "    查找所有 Python 文件"
echo ""
echo "  网络功能："
echo "    获取 https://example.com 的内容"
echo "    搜索 Python 最新版本"
echo ""
echo "────────────────────────────────────────────────────────────"
echo ""
echo "📚 文档："
echo ""
echo "  • FEATURES.md - 完整功能说明"
echo "  • QUICK_REFERENCE.md - 快速参考"
echo "  • SUMMARY.md - 升级总结"
echo ""
echo "────────────────────────────────────────────────────────────"
echo ""
echo "🔧 管理命令："
echo ""
echo "  启动: ./start.sh"
echo "  停止: ./stop.sh"
echo "  测试: python test_features.py"
echo "  验证: ./verify_upgrade.sh"
echo ""
echo "────────────────────────────────────────────────────────────"
echo ""

# 检查应用状态
if ps aux | grep -q "[p]ython app.py"; then
    echo "✅ 应用状态: 正在运行"
    echo ""
    echo "🚀 立即访问: http://localhost:5000"
else
    echo "⚠️  应用状态: 未运行"
    echo ""
    echo "启动应用: ./start.sh"
fi

echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "                    祝使用愉快！ 🎊"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
